/**
 * @file    diag_io.c
 * @brief   printf() redirection to USART1 (DUI-08). Overrides the weak _write()
 *          of the newlib syscalls generated by STM32CubeIDE.
 */
#include "main.h"

extern UART_HandleTypeDef huart1;

int _write(int fd, char *ptr, int len)
{
    (void)fd;
    if (HAL_UART_Transmit(&huart1, (uint8_t *)ptr, (uint16_t)len, 50u) != HAL_OK) {
        return -1;
    }
    return len;
}
